import { alpha, color, flattenColorGroups, oklch, tone } from "./colors";

const base = {
  bg: oklch(0.18, 0),
  bgDeep: oklch(0.16, 0),
  bgChrome: oklch(0.18, 0),
  fg: oklch(0.91, 0.01, 253.86),
  fgMuted: oklch(0.75, 0.02, 265.94),
  fgSubtle: oklch(0.64, 0.02, 276.15),
  border: oklch(0.22, 0),
  primary: oklch(0.77, 0.1, 174.53),
  info: oklch(0.73, 0.1, 250.24),
  success: oklch(0.77, 0.09, 129.94),
  warning: oklch(0.82, 0.09, 85.19),
  error: oklch(0.66, 0.12, 17.45),
  purple: oklch(0.67, 0.14, 314.88),
};

const ui = {
  base: {
    foreground: alpha(base.fg, 1),
    foregroundMuted: alpha(base.fgMuted, 1),
    foregroundSubtle: alpha(base.fgSubtle, 1),
    foregroundEditor: alpha(base.fgMuted, 1),
    foregroundTerminal: alpha(oklch(0.76, 0.02, 262.99), 1),
    foregroundInverse: color(oklch(1, 0)),
    foregroundWarningBadge: color(oklch(0.24, 0)),
    disabled: alpha(base.fgSubtle, 1),
    transparent: alpha(oklch(0, 0), 0),
  },
  surface: {
    title: color(base.bgChrome),
    titleInactive: color(base.bgDeep),
    editor: alpha(base.bg, 1),
    editorAlt: alpha(tone(base.bg, 0.01), 1),
    panel: alpha(base.bgDeep, 1),
    panelAlt: alpha(tone(base.bg, 0.04), 1),
    elevated: alpha(tone(base.bg, 0.08), 1),
    hover: alpha(base.fgMuted, 0.2),
    hoverMuted: alpha(tone(base.bg, 0.09), 1),
    selection: alpha(base.info, 0.24),
    selectionAlt: alpha(base.info, 0.18),
    lineHighlight: alpha(oklch(0.32, 0.03, 297.05), 0.37),
    indentGuide: oklch(0.84, 0.01, 264.5),
    terminal: alpha(oklch(0.19, 0), 1),
    terminalSelection: alpha(oklch(0.47, 0.02, 262.33), 0.4),
  },
  border: {
    default: alpha(base.border, 1),
    subtle: alpha(oklch(0.2, 0), 1),
    focus: alpha(oklch(0.49, 0.06, 217.8), 0.28),
  },
  accent: {
    primary: alpha(base.primary, 1),
    primaryHover: alpha(oklch(0.73, 0.07, 208.44), 1),
    blue: alpha(base.info, 1),
    blueSoft: alpha(base.info, 0.1),
    blueSelection: alpha(base.info, 0.24),
    cyanMatch: alpha(oklch(0.85, 0.1, 198.51), 0.4),
    greenSoft: alpha(oklch(0.85, 0.17, 138.38), 0.1),
    orangeMatch: alpha(oklch(0.79, 0.1, 66.47), 0.4),
  },
  state: {
    success: alpha(base.success, 1),
    modified: alpha(base.warning, 1),
    warning: alpha(base.warning, 1),
    warningSoft: alpha(base.warning, 0.1),
    warningBorder: alpha(oklch(0.43, 0.05, 80.2), 1),
    error: alpha(base.error, 1),
    errorSoft: alpha(base.error, 0.1),
    errorBorder: alpha(oklch(0.33, 0.05, 18.1), 1),
    infoBorder: alpha(oklch(0.35, 0.06, 261.37), 1),
  },
  scrollbar: {
    background: alpha(oklch(0.31, 0), 0.3),
    hover: alpha(oklch(0.32, 0), 1),
    active: alpha(oklch(0.49, 0), 0.62),
  },
  charts: {
    foreground: alpha(base.fg, 1),
    lines: alpha(oklch(0.84, 0.01, 264.5), 0.5),
    blue: alpha(base.info, 1),
    red: alpha(base.error, 1),
    yellow: alpha(base.warning, 1),
    orange: alpha(oklch(0.7, 0.08, 66.67), 1),
    green: alpha(base.success, 1),
    purple: alpha(base.purple, 1),
  },
};

const groups = {
  workbench: {
    "checkbox.border": ui.border.default,
    "editor.background": ui.surface.editor,
    "editor.foreground": ui.base.foregroundEditor,
    "editor.inactiveSelectionBackground": ui.accent.blueSelection,
    "editorIndentGuide.background1": alpha(ui.surface.indentGuide, 0.05),
    "editorIndentGuide.activeBackground1": alpha(ui.surface.indentGuide, 0.1),
    "editor.selectionHighlightBackground": ui.accent.blueSelection,
    "list.dropBackground": oklch(0.63, 0.02, 262.72, 0.5),
    "activityBarBadge.background": oklch(0.59, 0.07, 175),
    "sideBarTitle.foreground": ui.base.foreground,
    "input.placeholderForeground": ui.base.foregroundSubtle,
    "menu.background": ui.surface.editor,
    "menu.foreground": ui.base.foreground,
    "menu.separatorBackground": ui.border.default,
    "menu.border": ui.border.default,
    "menu.selectionBackground": ui.surface.selection,
    "statusBarItem.remoteForeground": ui.base.foregroundInverse,
    "statusBarItem.remoteBackground": ui.accent.blue,
    "ports.iconRunningProcessForeground": ui.state.success,
    "sideBarSectionHeader.background": ui.surface.panel,
    "sideBarSectionHeader.border": ui.border.default,
    "tab.selectedBackground": ui.surface.selection,
    "tab.selectedForeground": ui.base.foreground,
    "tab.lastPinnedBorder": ui.border.default,
    "list.activeSelectionIconForeground": ui.base.foregroundInverse,
    "terminal.inactiveSelectionBackground": ui.surface.terminalSelection,
    "widget.border": ui.border.default,
    "actionBar.toggledBackground": ui.surface.selectionAlt,
    "activityBar.activeBorder": ui.accent.primary,
    "activityBar.background": ui.surface.title,
    "activityBar.border": ui.border.subtle,
    "activityBar.foreground": ui.base.foreground,
    "activityBar.inactiveForeground": ui.base.foregroundMuted,
    "activityBarBadge.foreground": ui.base.foregroundInverse,
    "badge.background": oklch(0.66, 0.08, 174.01, 0.94),
    "badge.foreground": ui.base.foregroundInverse,
    "button.background": oklch(0.65, 0.08, 174.04, 0.95),
    "button.border": ui.border.subtle,
    "button.foreground": ui.base.foregroundInverse,
    "button.hoverBackground": ui.accent.primaryHover,
    "button.secondaryBackground": ui.base.transparent,
    "button.secondaryForeground": ui.base.foreground,
    "button.secondaryHoverBackground": ui.surface.hover,
    "chat.slashCommandBackground": ui.accent.blueSoft,
    "chat.slashCommandForeground": ui.accent.blue,
    "chat.editedFileForeground": ui.state.modified,
    "checkbox.background": ui.surface.panelAlt,
    "debugToolBar.background": ui.surface.editor,
    descriptionForeground: ui.base.foregroundMuted,
    "dropdown.background": ui.surface.panel,
    "dropdown.border": ui.border.default,
    "dropdown.foreground": ui.base.foreground,
    "dropdown.listBackground": ui.surface.panel,
  },
  editor: {
    "editor.findMatchBackground": ui.accent.cyanMatch,
    "editorGroup.border": ui.border.default,
    "editorGroupHeader.tabsBackground": ui.surface.panel,
    "editorGroupHeader.tabsBorder": ui.border.default,
    "editorGutter.addedBackground": ui.state.success,
    "editorGutter.deletedBackground": ui.state.error,
    "editorGutter.modifiedBackground": ui.state.modified,
    "editorLineNumber.activeForeground": oklch(0.87, 0.01, 258.34),
    "editorLineNumber.foreground": alpha(oklch(0.45, 0), 1),
    "editorOverviewRuler.border": ui.border.default,
    "editorWidget.background": ui.surface.editor,
    errorForeground: ui.state.error,
    focusBorder: ui.border.focus,
    foreground: ui.base.foreground,
    "icon.foreground": ui.base.foreground,
  },
  inputControls: {
    "input.background": ui.surface.panel,
    "input.border": ui.border.default,
    "input.foreground": ui.base.foreground,
    "inputOption.activeBackground": ui.accent.blueSoft,
    "inputOption.activeBorder": ui.border.default,
    "keybindingLabel.foreground": ui.base.foreground,
  },
  notificationsAndQuickInput: {
    "notificationCenterHeader.background": ui.surface.editor,
    "notificationCenterHeader.foreground": ui.base.foreground,
    "notifications.background": ui.surface.editor,
    "notifications.border": ui.border.default,
    "notifications.foreground": ui.base.foreground,
  },
  panelsAndSidebar: {
    "panel.background": ui.surface.panel,
    "panel.border": ui.border.subtle,
    "panelInput.border": ui.border.default,
    "panelTitle.activeBorder": ui.border.focus,
    "panelTitle.activeForeground": ui.base.foreground,
    "panelTitle.inactiveForeground": ui.base.foregroundMuted,
    "peekViewEditor.background": ui.surface.panel,
    "peekViewEditor.matchHighlightBackground": ui.accent.cyanMatch,
    "peekViewResult.background": ui.surface.panel,
    "peekViewResult.matchHighlightBackground": ui.accent.cyanMatch,
    "pickerGroup.border": ui.border.default,
    "progressBar.background": ui.accent.primary,
    "quickInput.background": ui.surface.editor,
    "quickInput.foreground": ui.base.foreground,
    "settings.dropdownBackground": ui.surface.editor,
    "settings.dropdownBorder": ui.border.default,
    "settings.headerForeground": ui.base.foregroundInverse,
    "settings.modifiedItemIndicator": alpha(base.warning, 0.4),
    "sideBar.background": ui.surface.panel,
    "sideBar.border": ui.border.subtle,
    "sideBar.foreground": ui.base.foreground,
    "sideBarSectionHeader.foreground": ui.base.foreground,
  },
  chrome: {
    "statusBar.background": ui.surface.title,
    "statusBar.border": ui.border.subtle,
    "statusBarItem.hoverBackground": ui.surface.hover,
    "statusBarItem.hoverForeground": ui.base.foregroundInverse,
    "statusBar.debuggingBackground": ui.accent.primary,
    "statusBar.debuggingForeground": ui.base.foregroundInverse,
    "statusBar.focusBorder": ui.border.focus,
    "statusBar.foreground": ui.base.foregroundMuted,
    "statusBar.noFolderBackground": ui.surface.title,
    "statusBarItem.focusBorder": ui.border.focus,
    "statusBarItem.prominentBackground": ui.accent.primary,
    "tab.activeBackground": ui.surface.editor,
    "tab.activeBorder": ui.surface.editor,
    "tab.activeBorderTop": ui.accent.primary,
    "tab.activeForeground": ui.base.foreground,
    "tab.selectedBorderTop": ui.accent.blue,
    "tab.border": ui.border.default,
    "tab.hoverBackground": ui.surface.editor,
    "tab.inactiveBackground": ui.surface.panel,
    "tab.inactiveForeground": ui.base.foregroundMuted,
    "tab.unfocusedActiveBorder": ui.surface.panel,
    "tab.unfocusedActiveBorderTop": ui.border.default,
    "tab.unfocusedHoverBackground": ui.surface.hoverMuted,
  },
  terminal: {
    "terminal.foreground": ui.base.foregroundTerminal,
    "terminal.tab.activeBorder": oklch(0.77, 0.1, 174.53),
  },
  textContent: {
    "textBlockQuote.background": ui.surface.panelAlt,
    "textBlockQuote.border": ui.border.default,
    "textCodeBlock.background": ui.surface.panelAlt,
    "textLink.activeForeground": ui.accent.primary,
    "textLink.foreground": ui.accent.primary,
    "textPreformat.foreground": ui.base.foregroundMuted,
    "textPreformat.background": ui.surface.elevated,
    "textSeparator.foreground": ui.border.default,
    "titleBar.activeBackground": ui.surface.title,
    "titleBar.activeForeground": ui.base.foregroundMuted,
    "titleBar.border": ui.border.subtle,
    "titleBar.inactiveBackground": ui.surface.titleInactive,
    "titleBar.inactiveForeground": ui.base.foregroundSubtle,
    "welcomePage.tileBackground": ui.surface.elevated,
    "welcomePage.progress.foreground": ui.accent.blue,
    disabledForeground: ui.base.disabled,
    "checkbox.foreground": ui.base.foregroundMuted,
    "inputOption.activeForeground": ui.base.foreground,
  },
  validation: {
    "inputValidation.infoBackground": ui.accent.blueSoft,
    "inputValidation.infoBorder": ui.state.infoBorder,
    "inputValidation.infoForeground": ui.base.foreground,
    "inputValidation.warningBackground": ui.state.warningSoft,
    "inputValidation.warningBorder": ui.state.warningBorder,
    "inputValidation.warningForeground": ui.base.foreground,
    "inputValidation.errorBackground": ui.state.errorSoft,
    "inputValidation.errorBorder": ui.state.errorBorder,
    "inputValidation.errorForeground": ui.base.foreground,
  },
  listsAndMenus: {
    "scrollbar.shadow": oklch(0, 0, 0, 0),
    "scrollbarSlider.background": oklch(0.31, 0, 0, 0.3),
    "scrollbarSlider.hoverBackground": oklch(0.32, 0, 0, 1),
    "scrollbarSlider.activeBackground": oklch(0.49, 0, 0, 0.62),
    "list.activeSelectionBackground": oklch(0.43, 0.02, 212.1, 0.65),
    "list.activeSelectionForeground": oklch(0.91, 0.01, 253.86, 1),
    "list.inactiveSelectionBackground": oklch(0.27, 0.02, 289.71, 1),
    "list.inactiveSelectionForeground": oklch(0.91, 0.01, 253.86, 1),
    "list.hoverBackground": oklch(0.38, 0.02, 191.6, 0.68),
    "list.hoverForeground": oklch(0.91, 0.01, 253.86, 1),
    "toolbar.hoverBackground": oklch(0.38, 0.02, 191.6, 0.68),
    "list.focusBackground": oklch(0.43, 0.02, 212.1, 0.65),
    "list.focusForeground": oklch(0.91, 0.01, 253.86, 1),
    "list.focusOutline": oklch(0.49, 0.06, 217.8, 0.28),
    "list.highlightForeground": oklch(0.77, 0.1, 174.53, 1),
    "list.invalidItemForeground": oklch(0.64, 0.02, 276.15, 1),
    "list.errorForeground": oklch(0.66, 0.12, 17.45, 1),
    "list.warningForeground": oklch(0.82, 0.09, 85.19, 1),
    "activityBar.activeFocusBorder": oklch(0.49, 0.06, 217.8, 0.28),
    "activityBarTop.activeBorder": oklch(0.77, 0.1, 174.53, 1),
    "menubar.selectionBackground": oklch(0.22, 0.02, 284.72, 1),
    "menubar.selectionForeground": oklch(0.91, 0.01, 253.86, 1),
    "menu.selectionForeground": oklch(0.91, 0.01, 253.86, 1),
    "commandCenter.foreground": oklch(0.91, 0.01, 253.86, 1),
    "commandCenter.activeForeground": oklch(0.91, 0.01, 253.86, 1),
    "commandCenter.background": oklch(0.18, 0),
    "commandCenter.activeBackground": oklch(0.38, 0.02, 191.6, 0.68),
    "commandCenter.border": oklch(0.22, 0, 0, 1),
  },
  editorDetails: {
    "editorStickyScroll.background": oklch(0.18, 0, 0, 1),
    "editorStickyScrollHover.background": oklch(0.16, 0, 0, 1),
    "editorStickyScroll.border": oklch(0.22, 0, 0, 1),
    "editorCursor.foreground": oklch(0.91, 0.01, 253.86, 1),
    "editor.selectionBackground": oklch(0.73, 0.1, 250.24, 0.24),
    "editor.wordHighlightBackground": oklch(0.85, 0.17, 138.38, 0.1),
    "editor.wordHighlightStrongBackground": oklch(0.47, 0.02, 262.33, 0.4),
    "editor.findMatchHighlightBackground": oklch(0.79, 0.1, 66.47, 0.4),
    "editor.findRangeHighlightBackground": oklch(0.16, 0, 0, 1),
    "editor.hoverHighlightBackground": oklch(0.16, 0, 0, 1),
    "editor.lineHighlightBackground": oklch(0.32, 0.03, 297.05, 0.37),
    "editor.rangeHighlightBackground": oklch(0.16, 0, 0, 1),
    "editorLink.activeForeground": oklch(0.77, 0.1, 174.53, 1),
    "editorWhitespace.foreground": oklch(0.64, 0.02, 276.15, 0.3),
    "editorIndentGuide.background": oklch(0.84, 0.01, 264.5, 0.05),
    "editorIndentGuide.activeBackground": oklch(0.84, 0.01, 264.5, 0.1),
    "editorRuler.foreground": oklch(0.84, 0.01, 264.5, 0.05),
    "editorCodeLens.foreground": oklch(0.64, 0.02, 276.15, 1),
    "editorBracketMatch.background": oklch(0.85, 0.1, 198.51, 0.4),
    "editorBracketMatch.border": oklch(0.22, 0, 0, 1),
    "editorBracketHighlight.foreground1": oklch(0.52, 0),
    "editorBracketHighlight.foreground2": oklch(0.48, 0),
    "editorBracketHighlight.foreground3": oklch(0.45, 0),
    "editorBracketHighlight.foreground4": oklch(0.4, 0),
    "editorBracketHighlight.foreground5": oklch(0.39, 0),
    "editorBracketHighlight.foreground6": oklch(0.47, 0),
    "editorBracketHighlight.unexpectedBracket.foreground": oklch(
      0.66,
      0.12,
      17.45,
      1,
    ),
    "editorWidget.border": oklch(0.22, 0, 0, 1),
    "editorWidget.foreground": oklch(0.91, 0.01, 253.86, 1),
    "editorSuggestWidget.background": oklch(0.18, 0, 0, 1),
    "editorSuggestWidget.border": oklch(0.22, 0, 0, 1),
    "editorSuggestWidget.foreground": oklch(0.91, 0.01, 253.86, 1),
    "editorSuggestWidget.highlightForeground": oklch(0.77, 0.1, 174.53, 1),
    "editorSuggestWidget.selectedBackground": oklch(0.43, 0.02, 212.1, 0.65),
    "editorHoverWidget.background": oklch(0.18, 0, 0, 1),
    "editorHoverWidget.border": oklch(0.22, 0, 0, 1),
    "peekView.border": oklch(0.2, 0, 0, 1),
    "peekViewResult.fileForeground": oklch(0.91, 0.01, 253.86, 1),
    "peekViewResult.lineForeground": oklch(0.75, 0.02, 265.94, 1),
    "peekViewResult.selectionBackground": oklch(0.43, 0.02, 212.1, 0.65),
    "peekViewResult.selectionForeground": oklch(0.91, 0.01, 253.86, 1),
    "peekViewTitle.background": oklch(0.16, 0, 0, 1),
    "peekViewTitleDescription.foreground": oklch(0.75, 0.02, 265.94, 1),
    "peekViewTitleLabel.foreground": oklch(0.91, 0.01, 253.86, 1),
    "editorGutter.background": oklch(0.18, 0, 0, 1),
  },
  diffAndGit: {
    "diffEditor.insertedLineBackground": oklch(0.77, 0.09, 129.94, 0.1),
    "diffEditor.insertedTextBackground": oklch(0.62, 0.16, 147.25, 0.35),
    "diffEditor.removedLineBackground": oklch(0.66, 0.12, 17.45, 0.1),
    "diffEditor.removedTextBackground": oklch(0.37, 0.14, 21.08, 0.8),
    "editorOverviewRuler.findMatchForeground": oklch(0.85, 0.1, 198.51, 0.4),
    "editorOverviewRuler.modifiedForeground": oklch(0.82, 0.09, 85.19, 1),
    "editorOverviewRuler.addedForeground": oklch(0.77, 0.09, 129.94, 1),
    "editorOverviewRuler.deletedForeground": oklch(0.66, 0.12, 17.45, 1),
    "editorOverviewRuler.errorForeground": oklch(0.66, 0.12, 17.45, 1),
    "editorOverviewRuler.warningForeground": oklch(0.82, 0.09, 85.19, 1),
    "statusBar.noFolderForeground": oklch(0.75, 0.02, 265.94, 1),
    "statusBarItem.activeBackground": oklch(0.43, 0.02, 218.3, 0.59),
    "statusBarItem.prominentForeground": oklch(1, 0),
    "statusBarItem.prominentHoverBackground": oklch(0.73, 0.07, 208.44, 1),
    "tab.hoverForeground": oklch(0.91, 0.01, 253.86, 1),
    "tab.unfocusedActiveBackground": oklch(0.18, 0, 0, 1),
    "tab.unfocusedActiveForeground": oklch(0.75, 0.02, 265.94, 1),
    "tab.unfocusedInactiveBackground": oklch(0.16, 0, 0, 1),
    "tab.unfocusedInactiveForeground": oklch(0.64, 0.02, 276.15, 1),
    "breadcrumb.foreground": oklch(0.75, 0.02, 265.94, 1),
    "breadcrumb.background": oklch(0.18, 0, 0, 1),
    "breadcrumb.focusForeground": oklch(0.91, 0.01, 253.86, 1),
    "breadcrumb.activeSelectionForeground": oklch(0.91, 0.01, 253.86, 1),
    "breadcrumbPicker.background": oklch(0.18, 0, 0, 1),
    "notificationCenter.border": oklch(0.22, 0, 0, 1),
    "notificationToast.border": oklch(0.22, 0, 0, 1),
    "notificationLink.foreground": oklch(0.77, 0.1, 174.53, 1),
    "notificationsWarningIcon.foreground": oklch(0.82, 0.09, 85.19, 1),
    "notificationsErrorIcon.foreground": oklch(0.66, 0.12, 17.45, 1),
    "notificationsInfoIcon.foreground": oklch(0.73, 0.1, 250.24, 1),
    "activityWarningBadge.foreground": oklch(0.24, 0),
    "activityWarningBadge.background": oklch(0.82, 0.09, 85.19, 1),
    "activityErrorBadge.foreground": oklch(1, 0),
    "activityErrorBadge.background": oklch(0.66, 0.12, 17.45, 1),
    "extensionButton.prominentBackground": oklch(0.77, 0.1, 174.53, 1),
    "extensionButton.prominentForeground": oklch(1, 0),
    "extensionButton.prominentHoverBackground": oklch(0.73, 0.07, 208.44, 1),
    "pickerGroup.foreground": oklch(0.91, 0.01, 253.86, 1),
    "quickInputList.focusBackground": oklch(0.43, 0.02, 212.1, 0.65),
    "quickInputList.focusForeground": oklch(0.91, 0.01, 253.86, 1),
    "quickInputList.focusIconForeground": oklch(0.91, 0.01, 253.86, 1),
    "quickInputList.hoverBackground": oklch(0.38, 0.02, 191.6, 0.68),
    "terminal.selectionBackground": oklch(0.73, 0.1, 250.24, 0.24),
    "terminal.background": oklch(0.19, 0, 0, 1),
    "terminal.border": oklch(0.22, 0, 0, 1),
    "terminalCursor.foreground": oklch(0.91, 0.01, 253.86, 1),
    "terminalCursor.background": oklch(0.19, 0, 0, 1),
    "terminal.ansiBlack": oklch(0.2, 0, 0, 1),
    "terminal.ansiBrightBlack": oklch(0.43, 0, 0, 1),
    "terminal.ansiRed": oklch(0.67, 0.14, 17, 1),
    "terminal.ansiBrightRed": oklch(0.73, 0.12, 16.81, 1),
    "terminal.ansiGreen": oklch(0.77, 0.11, 133, 1),
    "terminal.ansiBrightGreen": oklch(0.82, 0.12, 130.72, 1),
    "terminal.ansiYellow": oklch(0.82, 0.1, 82.26, 1),
    "terminal.ansiBrightYellow": oklch(0.9, 0.11, 85.08, 1),
    "terminal.ansiBlue": oklch(0.73, 0.12, 245.3, 1),
    "terminal.ansiBrightBlue": oklch(0.79, 0.11, 250.11, 1),
    "terminal.ansiMagenta": oklch(0.64, 0.15, 295.13, 1),
    "terminal.ansiBrightMagenta": oklch(0.74, 0.12, 298.93, 1),
    "terminal.ansiCyan": oklch(0.72, 0.09, 206.31, 1),
    "terminal.ansiBrightCyan": oklch(0.81, 0.1, 202.97, 1),
    "terminal.ansiWhite": oklch(0.76, 0.02, 262.99, 1),
    "terminal.ansiBrightWhite": oklch(0.99, 0, 0, 1),
    "gitDecoration.addedResourceForeground": oklch(0.77, 0.09, 129.94, 1),
    "gitDecoration.modifiedResourceForeground": oklch(0.82, 0.09, 85.19, 1),
    "gitDecoration.deletedResourceForeground": oklch(0.66, 0.12, 17.45, 1),
    "gitDecoration.untrackedResourceForeground": oklch(0.77, 0.09, 129.94, 1),
    "gitDecoration.ignoredResourceForeground": oklch(0.64, 0.02, 276.15, 1),
    "gitDecoration.conflictingResourceForeground": oklch(0.66, 0.12, 17.45, 1),
    "gitDecoration.stageModifiedResourceForeground": oklch(
      0.82,
      0.09,
      85.19,
      1,
    ),
    "gitDecoration.stageDeletedResourceForeground": oklch(0.66, 0.12, 17.45, 1),
    "quickInputTitle.background": oklch(0.18, 0, 0, 1),
    "commandCenter.activeBorder": oklch(0.22, 0, 0, 1),
    "quickInput.border": oklch(0.22, 0, 0, 1),
  },
  gaugesAndChat: {
    "gauge.foreground": oklch(0.73, 0.1, 250.24, 1),
    "gauge.background": oklch(0.73, 0.1, 250.24, 0.1),
    "gauge.border": oklch(0.35, 0.06, 261.37, 1),
    "gauge.warningForeground": oklch(0.82, 0.09, 85.19, 1),
    "gauge.warningBackground": oklch(0.82, 0.09, 85.19, 0.1),
    "gauge.errorForeground": oklch(0.66, 0.12, 17.45, 1),
    "gauge.errorBackground": oklch(0.66, 0.12, 17.45, 0.1),
    "chat.requestBubbleBackground": oklch(0.22, 0.02, 284.72, 1),
    "chat.requestBubbleHoverBackground": oklch(0.27, 0.02, 289.71, 1),
    "editorCommentsWidget.rangeBackground": oklch(0.73, 0.1, 250.24, 0.1),
    "editorCommentsWidget.rangeActiveBackground": oklch(
      0.73,
      0.1,
      250.24,
      0.24,
    ),
  },
  chartsAndInline: {
    "charts.foreground": oklch(0.91, 0.01, 253.86, 1),
    "charts.lines": oklch(0.84, 0.01, 264.5, 0.5),
    "charts.blue": oklch(0.73, 0.1, 250.24, 1),
    "charts.red": oklch(0.66, 0.12, 17.45, 1),
    "charts.yellow": oklch(0.82, 0.09, 85.19, 1),
    "charts.orange": oklch(0.7, 0.08, 66.67, 1),
    "charts.green": oklch(0.77, 0.09, 129.94, 1),
    "charts.purple": oklch(0.67, 0.14, 314.88, 1),
    "inlineChat.border": oklch(0, 0, 0, 0),
    "minimapSlider.background": oklch(0.31, 0, 0, 0.3),
    "minimapSlider.hoverBackground": oklch(0.32, 0, 0, 1),
    "minimapSlider.activeBackground": oklch(0.49, 0, 0, 0.62),
  },
};

export const DarkUiTheme = flattenColorGroups(groups);
