import { alpha, color, flattenColorGroups, tone } from "../colors";

const base = {
  bg: color`oklch(18% 0 0)`,
  bgDeep: tone(color`oklch(18% 0 0)`, -0.02),
  fg: color`oklch(91% 0.01 253.86)`,
  fgMuted: color`oklch(75% 0.02 265.94)`,
  fgSubtle: color`oklch(64% 0.02 276.15)`,
  border: color`oklch(22% 0 0)`,
  primary: color`oklch(65% 0.1 174.53)`,
  info: color`oklch(73% 0.1 250.24)`,
  success: color`oklch(77% 0.09 129.94)`,
  warning: color`oklch(82% 0.09 85.19)`,
  error: color`oklch(66% 0.12 17.45)`,
  purple: color`oklch(67% 0.14 314.88)`,
};

const ui = {
  base: {
    foreground: alpha(base.fg, 1),
    foregroundMuted: alpha(base.fgMuted, 1),
    foregroundSubtle: alpha(base.fgSubtle, 1),
    foregroundEditor: alpha(base.fgMuted, 1),
    foregroundTerminal: alpha(color`oklch(76% 0.02 262.99)`, 1),
    foregroundInverse: color`oklch(100% 0 0)`,
    foregroundWarningBadge: color`oklch(24% 0 0)`,
    disabled: alpha(base.fgSubtle, 1),
    transparent: alpha(color`oklch(0% 0 0)`, 0),
  },
  surface: {
    title: color(base.bg),
    titleInactive: color(base.bgDeep),
    editor: alpha(base.bg, 1),
    editorAlt: alpha(tone(base.bg, 0.01), 1),
    panel: alpha(base.bgDeep, 1),
    panelAlt: alpha(tone(base.bg, 0.04), 1),
    elevated: alpha(tone(base.bg, 0.08), 1),
    hover: alpha(base.fgMuted, 0.2),
    hoverMuted: alpha(tone(base.bg, 0.09), 1),
    selection: alpha(base.info, 0.24),
    selectionAlt: alpha(base.info, 0.18),
    lineHighlight: alpha(base.fg, 0.08),
    indentGuide: base.fgMuted,
    terminal: alpha(tone(base.bg, 0.01), 1),
    terminalSelection: alpha(base.info, 0.32),
  },
  border: {
    default: alpha(base.border, 1),
    subtle: alpha(tone(base.border, -0.02), 1),
    focus: alpha(base.info, 0.28),
  },
  accent: {
    primary: alpha(base.primary, 1),
    primaryHover: alpha(tone(base.primary, -0.04), 1),
    blue: alpha(base.info, 1),
    blueSoft: alpha(base.info, 0.1),
    blueSelection: alpha(base.info, 0.24),
    cyanMatch: alpha(base.info, 0.4),
    greenSoft: alpha(base.success, 0.1),
    orangeMatch: alpha(base.warning, 0.4),
  },
  state: {
    success: alpha(base.success, 1),
    modified: alpha(base.warning, 1),
    warning: alpha(base.warning, 1),
    warningSoft: alpha(base.warning, 0.1),
    warningBorder: alpha(tone(base.warning, -0.39), 1),
    error: alpha(base.error, 1),
    errorSoft: alpha(base.error, 0.1),
    errorBorder: alpha(tone(base.error, -0.33), 1),
    infoBorder: alpha(tone(base.info, -0.38), 1),
  },
  scrollbar: {
    background: alpha(base.fgSubtle, 0.15),
    hover: alpha(base.fgSubtle, 0.25),
    active: alpha(base.fgSubtle, 0.33),
  },
  charts: {
    foreground: alpha(base.fg, 1),
    lines: alpha(base.fgMuted, 0.5),
    blue: alpha(base.info, 1),
    red: alpha(base.error, 1),
    yellow: alpha(base.warning, 1),
    orange: alpha(color`oklch(70% 0.08 66.67)`, 1),
    green: alpha(base.success, 1),
    purple: alpha(base.purple, 1),
  },
};

const groups = {
  workbench: {
    "checkbox.border": ui.border.default,
    "editor.background": ui.surface.editor,
    "editor.foreground": ui.base.foregroundEditor,
    "editor.inactiveSelectionBackground": ui.accent.blueSelection,
    "editorIndentGuide.background1": alpha(ui.surface.indentGuide, 0.05),
    "editorIndentGuide.activeBackground1": alpha(ui.surface.indentGuide, 0.1),
    "editor.selectionHighlightBackground": ui.accent.blueSelection,
    "list.dropBackground": color`oklch(63% 0.02 262.72 / 50%)`,
    "activityBarBadge.background": color`oklch(59% 0.07 175)`,
    "sideBarTitle.foreground": ui.base.foreground,
    "input.placeholderForeground": ui.base.foregroundSubtle,
    "menu.background": ui.surface.panel,
    "menu.foreground": ui.base.foreground,
    "menu.separatorBackground": ui.border.default,
    "menu.border": ui.border.default,
    "menu.selectionBackground": ui.surface.selection,
    "statusBarItem.remoteForeground": ui.base.foregroundInverse,
    "statusBarItem.remoteBackground": ui.accent.blue,
    "ports.iconRunningProcessForeground": ui.state.success,
    "sideBarSectionHeader.background": ui.surface.panel,
    "sideBarSectionHeader.border": ui.border.default,
    "tab.selectedBackground": ui.surface.selection,
    "tab.selectedForeground": ui.base.foreground,
    "tab.lastPinnedBorder": ui.border.default,
    "list.activeSelectionIconForeground": ui.base.foregroundInverse,
    "terminal.inactiveSelectionBackground": ui.surface.terminalSelection,
    "widget.border": ui.border.default,
    "actionBar.toggledBackground": ui.surface.selectionAlt,
    "activityBar.activeBorder": ui.accent.primary,
    "activityBar.background": ui.surface.panel,
    "activityBar.border": ui.border.subtle,
    "activityBar.foreground": ui.base.foreground,
    "activityBar.inactiveForeground": ui.base.foregroundMuted,
    "activityBarBadge.foreground": ui.base.foregroundInverse,
    "badge.background": color`oklch(66% 0.08 174.01 / 94%)`,
    "badge.foreground": ui.base.foregroundInverse,
    "button.background": color`oklch(65% 0.08 174.04 / 95%)`,
    "button.border": ui.border.subtle,
    "button.foreground": ui.base.foregroundInverse,
    "button.hoverBackground": ui.accent.primaryHover,
    "button.secondaryBackground": ui.base.transparent,
    "button.secondaryForeground": ui.base.foreground,
    "button.secondaryHoverBackground": ui.surface.hover,
    "chat.slashCommandBackground": ui.accent.blueSoft,
    "chat.slashCommandForeground": ui.accent.blue,
    "chat.editedFileForeground": ui.state.modified,
    "checkbox.background": ui.surface.panelAlt,
    "debugToolBar.background": ui.surface.panel,
    descriptionForeground: ui.base.foregroundMuted,
    "dropdown.background": ui.surface.panel,
    "dropdown.border": ui.border.default,
    "dropdown.foreground": ui.base.foreground,
    "dropdown.listBackground": ui.surface.panel,
  },
  editor: {
    "editor.findMatchBackground": ui.accent.cyanMatch,
    "editorGroup.border": ui.border.default,
    "editorGroupHeader.tabsBackground": ui.surface.panel,
    "editorGroupHeader.tabsBorder": ui.border.default,
    "editorGutter.addedBackground": ui.state.success,
    "editorGutter.deletedBackground": ui.state.error,
    "editorGutter.modifiedBackground": ui.state.modified,
    "editorLineNumber.activeForeground": color`oklch(87% 0.01 258.34)`,
    "editorLineNumber.foreground": alpha(color`oklch(45% 0 0)`, 1),
    "editorOverviewRuler.border": ui.border.default,
    "editorWidget.background": ui.surface.editor,
    errorForeground: ui.state.error,
    focusBorder: ui.border.focus,
    foreground: ui.base.foreground,
    "icon.foreground": ui.base.foreground,
  },
  inputControls: {
    "input.background": ui.surface.panel,
    "input.border": ui.border.default,
    "input.foreground": ui.base.foreground,
    "inputOption.activeBackground": ui.accent.blueSoft,
    "inputOption.activeBorder": ui.border.default,
    "keybindingLabel.foreground": ui.base.foreground,
  },
  notificationsAndQuickInput: {
    "notificationCenterHeader.background": ui.surface.editor,
    "notificationCenterHeader.foreground": ui.base.foreground,
    "notifications.background": ui.surface.editor,
    "notifications.border": ui.border.default,
    "notifications.foreground": ui.base.foreground,
  },
  panelsAndSidebar: {
    "panel.background": ui.surface.panel,
    "panel.border": ui.border.subtle,
    "panelInput.border": ui.border.default,
    "panelTitle.activeBorder": ui.border.focus,
    "panelTitle.activeForeground": ui.base.foreground,
    "panelTitle.inactiveForeground": ui.base.foregroundMuted,
    "peekViewEditor.background": ui.surface.panel,
    "peekViewEditor.matchHighlightBackground": ui.accent.cyanMatch,
    "peekViewResult.background": ui.surface.panel,
    "peekViewResult.matchHighlightBackground": ui.accent.cyanMatch,
    "pickerGroup.border": ui.border.default,
    "progressBar.background": ui.accent.primary,
    "quickInput.background": ui.surface.editor,
    "quickInput.foreground": ui.base.foreground,
    "settings.dropdownBackground": ui.surface.editor,
    "settings.dropdownBorder": ui.border.default,
    "settings.headerForeground": ui.base.foregroundInverse,
    "settings.modifiedItemIndicator": alpha(base.warning, 0.4),
    "sideBar.background": ui.surface.panel,
    "sideBar.border": ui.border.subtle,
    "sideBar.foreground": ui.base.foreground,
    "sideBarSectionHeader.foreground": ui.base.foreground,
  },
  chrome: {
    "statusBar.background": ui.surface.panel,
    "statusBar.border": ui.border.subtle,
    "statusBarItem.hoverBackground": ui.surface.hover,
    "statusBarItem.hoverForeground": ui.base.foregroundInverse,
    "statusBar.debuggingBackground": ui.accent.primary,
    "statusBar.debuggingForeground": ui.base.foregroundInverse,
    "statusBar.focusBorder": ui.border.focus,
    "statusBar.foreground": ui.base.foregroundMuted,
    "statusBar.noFolderBackground": ui.surface.title,
    "statusBarItem.focusBorder": ui.border.focus,
    "statusBarItem.prominentBackground": ui.accent.primary,
    "tab.activeBackground": ui.surface.panel,
    "tab.activeBorder": ui.surface.editor,
    "tab.activeBorderTop": ui.accent.primary,
    "tab.activeForeground": ui.base.foreground,
    "tab.selectedBorderTop": ui.accent.blue,
    "tab.border": ui.border.default,
    "tab.hoverBackground": ui.surface.editor,
    "tab.inactiveBackground": ui.surface.panel,
    "tab.inactiveForeground": ui.base.foregroundMuted,
    "tab.unfocusedActiveBorder": ui.surface.panel,
    "tab.unfocusedActiveBorderTop": ui.border.default,
    "tab.unfocusedHoverBackground": ui.surface.hoverMuted,
  },
  terminal: {
    "terminal.foreground": ui.base.foregroundTerminal,
    "terminal.tab.activeBorder": ui.accent.primary,
  },
  textContent: {
    "textBlockQuote.background": ui.surface.panelAlt,
    "textBlockQuote.border": ui.border.default,
    "textCodeBlock.background": ui.surface.panelAlt,
    "textLink.activeForeground": ui.accent.primary,
    "textLink.foreground": ui.accent.primary,
    "textPreformat.foreground": ui.base.foregroundMuted,
    "textPreformat.background": ui.surface.elevated,
    "textSeparator.foreground": ui.border.default,
    "titleBar.activeBackground": ui.surface.panel,
    "titleBar.activeForeground": ui.base.foregroundMuted,
    "titleBar.border": ui.border.subtle,
    "titleBar.inactiveBackground": ui.surface.panel,
    "titleBar.inactiveForeground": ui.base.foregroundSubtle,
    "welcomePage.tileBackground": ui.surface.elevated,
    "welcomePage.progress.foreground": ui.accent.blue,
    disabledForeground: ui.base.disabled,
    "checkbox.foreground": ui.base.foregroundMuted,
    "inputOption.activeForeground": ui.base.foreground,
  },
  validation: {
    "inputValidation.infoBackground": ui.accent.blueSoft,
    "inputValidation.infoBorder": ui.state.infoBorder,
    "inputValidation.infoForeground": ui.base.foreground,
    "inputValidation.warningBackground": ui.state.warningSoft,
    "inputValidation.warningBorder": ui.state.warningBorder,
    "inputValidation.warningForeground": ui.base.foreground,
    "inputValidation.errorBackground": ui.state.errorSoft,
    "inputValidation.errorBorder": ui.state.errorBorder,
    "inputValidation.errorForeground": ui.base.foreground,
  },
  listsAndMenus: {
    "scrollbar.shadow": ui.base.transparent,
    "scrollbarSlider.background": ui.scrollbar.background,
    "scrollbarSlider.hoverBackground": ui.scrollbar.hover,
    "scrollbarSlider.activeBackground": ui.scrollbar.active,
    "list.activeSelectionBackground": ui.surface.selection,
    "list.activeSelectionForeground": ui.base.foreground,
    "list.inactiveSelectionBackground": ui.surface.hoverMuted,
    "list.inactiveSelectionForeground": ui.base.foreground,
    "list.hoverBackground": ui.surface.hover,
    "list.hoverForeground": ui.base.foreground,
    "toolbar.hoverBackground": ui.surface.hover,
    "list.focusBackground": ui.surface.selection,
    "list.focusForeground": ui.base.foreground,
    "list.focusOutline": ui.border.focus,
    "list.highlightForeground": ui.accent.primary,
    "list.invalidItemForeground": ui.base.foregroundSubtle,
    "list.errorForeground": ui.state.error,
    "list.warningForeground": ui.state.warning,
    "activityBar.activeFocusBorder": ui.border.focus,
    "activityBarTop.activeBorder": ui.accent.primary,
    "menubar.selectionBackground": ui.surface.panelAlt,
    "menubar.selectionForeground": ui.base.foreground,
    "menu.selectionForeground": ui.base.foreground,
    "commandCenter.foreground": ui.base.foreground,
    "commandCenter.activeForeground": ui.base.foreground,
    "commandCenter.background": ui.surface.editor,
    "commandCenter.activeBackground": ui.surface.hover,
    "commandCenter.border": ui.border.default,
  },
  editorDetails: {
    "editorStickyScroll.background": ui.surface.editor,
    "editorStickyScrollHover.background": ui.surface.panel,
    "editorStickyScroll.border": ui.border.default,
    "editorCursor.foreground": ui.base.foreground,
    "editor.selectionBackground": ui.accent.blueSelection,
    "editor.wordHighlightBackground": ui.accent.greenSoft,
    "editor.wordHighlightStrongBackground": ui.surface.terminalSelection,
    "editor.findMatchHighlightBackground": ui.accent.orangeMatch,
    "editor.findRangeHighlightBackground": ui.surface.panel,
    "editor.hoverHighlightBackground": ui.surface.panel,
    "editor.lineHighlightBackground": ui.surface.lineHighlight,
    "editor.rangeHighlightBackground": ui.surface.panel,
    "editorLink.activeForeground": ui.accent.primary,
    "editorWhitespace.foreground": alpha(base.fgSubtle, 0.3),
    "editorIndentGuide.background": alpha(ui.surface.indentGuide, 0.05),
    "editorIndentGuide.activeBackground": alpha(ui.surface.indentGuide, 0.1),
    "editorRuler.foreground": alpha(ui.surface.indentGuide, 0.05),
    "editorCodeLens.foreground": ui.base.foregroundSubtle,
    "editorBracketMatch.background": ui.accent.cyanMatch,
    "editorBracketMatch.border": ui.border.default,
    "editorBracketHighlight.foreground1": color`oklch(52% 0 0)`,
    "editorBracketHighlight.foreground2": color`oklch(54% 0 0)`,
    "editorBracketHighlight.foreground3": color`oklch(56% 0 0)`,
    "editorBracketHighlight.foreground4": color`oklch(58% 0 0)`,
    "editorBracketHighlight.foreground5": color`oklch(56% 0 0)`,
    "editorBracketHighlight.foreground6": color`oklch(54% 0 0)`,
    "editorBracketHighlight.unexpectedBracket.foreground": ui.state.error,
    "editorWidget.border": ui.border.default,
    "editorWidget.foreground": ui.base.foreground,
    "editorSuggestWidget.background": ui.surface.editor,
    "editorSuggestWidget.border": ui.border.default,
    "editorSuggestWidget.foreground": ui.base.foreground,
    "editorSuggestWidget.highlightForeground": ui.accent.primary,
    "editorSuggestWidget.selectedBackground": ui.surface.selection,
    "editorHoverWidget.background": ui.surface.editor,
    "editorHoverWidget.border": ui.border.default,
    "peekView.border": ui.border.subtle,
    "peekViewResult.fileForeground": ui.base.foreground,
    "peekViewResult.lineForeground": ui.base.foregroundMuted,
    "peekViewResult.selectionBackground": ui.surface.selection,
    "peekViewResult.selectionForeground": ui.base.foreground,
    "peekViewTitle.background": ui.surface.panel,
    "peekViewTitleDescription.foreground": ui.base.foregroundMuted,
    "peekViewTitleLabel.foreground": ui.base.foreground,
    "editorGutter.background": ui.surface.editor,
  },
  diffAndGit: {
    "diffEditor.insertedLineBackground": ui.state.warningSoft,
    "diffEditor.insertedTextBackground": alpha(base.success, 0.35),
    "diffEditor.removedLineBackground": ui.state.errorSoft,
    "diffEditor.removedTextBackground": alpha(base.error, 0.8),
    "editorOverviewRuler.findMatchForeground": ui.accent.cyanMatch,
    "editorOverviewRuler.modifiedForeground": ui.state.modified,
    "editorOverviewRuler.addedForeground": ui.state.success,
    "editorOverviewRuler.deletedForeground": ui.state.error,
    "editorOverviewRuler.errorForeground": ui.state.error,
    "editorOverviewRuler.warningForeground": ui.state.warning,
    "statusBar.noFolderForeground": ui.base.foregroundMuted,
    "statusBarItem.activeBackground": ui.surface.selectionAlt,
    "statusBarItem.prominentForeground": ui.base.foregroundInverse,
    "statusBarItem.prominentHoverBackground": ui.accent.primaryHover,
    "tab.hoverForeground": ui.base.foreground,
    "tab.unfocusedActiveBackground": ui.surface.editor,
    "tab.unfocusedActiveForeground": ui.base.foregroundMuted,
    "tab.unfocusedInactiveBackground": ui.surface.panel,
    "tab.unfocusedInactiveForeground": ui.base.foregroundSubtle,
    "breadcrumb.foreground": ui.base.foregroundMuted,
    "breadcrumb.background": ui.surface.editor,
    "breadcrumb.focusForeground": ui.base.foreground,
    "breadcrumb.activeSelectionForeground": ui.base.foreground,
    "breadcrumbPicker.background": ui.surface.editor,
    "notificationCenter.border": ui.border.default,
    "notificationToast.border": ui.border.default,
    "notificationLink.foreground": ui.accent.primary,
    "notificationsWarningIcon.foreground": ui.state.warning,
    "notificationsErrorIcon.foreground": ui.state.error,
    "notificationsInfoIcon.foreground": ui.accent.blue,
    "activityWarningBadge.foreground": ui.base.foregroundWarningBadge,
    "activityWarningBadge.background": ui.state.warning,
    "activityErrorBadge.foreground": ui.base.foregroundInverse,
    "activityErrorBadge.background": ui.state.error,
    "extensionButton.prominentBackground": ui.accent.primary,
    "extensionButton.prominentForeground": ui.base.foregroundInverse,
    "extensionButton.prominentHoverBackground": ui.accent.primaryHover,
    "pickerGroup.foreground": ui.base.foreground,
    "quickInputList.focusBackground": ui.surface.selection,
    "quickInputList.focusForeground": ui.base.foreground,
    "quickInputList.focusIconForeground": ui.base.foreground,
    "quickInputList.hoverBackground": ui.surface.hover,
    "terminal.selectionBackground": ui.accent.blueSelection,
    "terminal.background": ui.surface.terminal,
    "terminal.border": ui.border.default,
    "terminalCursor.foreground": ui.base.foreground,
    "terminalCursor.background": ui.surface.terminal,
    "terminal.ansiBlack": color`oklch(20% 0 0 / 100%)`,
    "terminal.ansiBrightBlack": color`oklch(43% 0 0 / 100%)`,
    "terminal.ansiRed": color`oklch(67% 0.14 17 / 100%)`,
    "terminal.ansiBrightRed": color`oklch(73% 0.12 16.81 / 100%)`,
    "terminal.ansiGreen": color`oklch(77% 0.11 133 / 100%)`,
    "terminal.ansiBrightGreen": color`oklch(82% 0.12 130.72 / 100%)`,
    "terminal.ansiYellow": color`oklch(82% 0.1 82.26 / 100%)`,
    "terminal.ansiBrightYellow": color`oklch(90% 0.11 85.08 / 100%)`,
    "terminal.ansiBlue": color`oklch(73% 0.12 245.3 / 100%)`,
    "terminal.ansiBrightBlue": color`oklch(79% 0.11 250.11 / 100%)`,
    "terminal.ansiMagenta": color`oklch(64% 0.15 295.13 / 100%)`,
    "terminal.ansiBrightMagenta": color`oklch(74% 0.12 298.93 / 100%)`,
    "terminal.ansiCyan": color`oklch(72% 0.09 206.31 / 100%)`,
    "terminal.ansiBrightCyan": color`oklch(81% 0.1 202.97 / 100%)`,
    "terminal.ansiWhite": color`oklch(76% 0.02 262.99 / 100%)`,
    "terminal.ansiBrightWhite": color`oklch(99% 0 0 / 100%)`,
    "gitDecoration.addedResourceForeground": ui.state.success,
    "gitDecoration.modifiedResourceForeground": ui.state.modified,
    "gitDecoration.deletedResourceForeground": ui.state.error,
    "gitDecoration.untrackedResourceForeground": ui.state.success,
    "gitDecoration.ignoredResourceForeground": ui.base.foregroundSubtle,
    "gitDecoration.conflictingResourceForeground": ui.state.error,
    "gitDecoration.stageModifiedResourceForeground": ui.state.modified,
    "gitDecoration.stageDeletedResourceForeground": ui.state.error,
    "quickInputTitle.background": ui.surface.editor,
    "commandCenter.activeBorder": ui.border.default,
    "quickInput.border": ui.border.default,
  },
  gaugesAndChat: {
    "gauge.foreground": ui.accent.blue,
    "gauge.background": ui.accent.blueSoft,
    "gauge.border": ui.state.infoBorder,
    "gauge.warningForeground": ui.state.warning,
    "gauge.warningBackground": ui.state.warningSoft,
    "gauge.errorForeground": ui.state.error,
    "gauge.errorBackground": ui.state.errorSoft,
    "chat.requestBubbleBackground": ui.surface.panelAlt,
    "chat.requestBubbleHoverBackground": ui.surface.hoverMuted,
    "editorCommentsWidget.rangeBackground": ui.accent.blueSoft,
    "editorCommentsWidget.rangeActiveBackground": ui.accent.blueSelection,
  },
  chartsAndInline: {
    "charts.foreground": ui.charts.foreground,
    "charts.lines": ui.charts.lines,
    "charts.blue": ui.charts.blue,
    "charts.red": ui.charts.red,
    "charts.yellow": ui.charts.yellow,
    "charts.orange": ui.charts.orange,
    "charts.green": ui.charts.green,
    "charts.purple": ui.charts.purple,
    "inlineChat.border": ui.base.transparent,
    "minimapSlider.background": ui.scrollbar.background,
    "minimapSlider.hoverBackground": ui.scrollbar.hover,
    "minimapSlider.activeBackground": ui.scrollbar.active,
  },
};

export const DarkUiTheme = flattenColorGroups(groups);
