import { alpha, color, flattenColorGroups, tone } from "../colors";

const base = {
  bg: color`oklch(100% 0 0)`,
  bgWorkbench: tone(color`oklch(100% 0 0)`, -0.03),
  bgControl: tone(color`oklch(100% 0 0)`, -0.06),
  fg: color`oklch(31% 0.01 242)`,
  fgMuted: color`oklch(58% 0.02 250.38)`,
  fgSubtle: color`oklch(67% 0.02 245.2)`,
  border: color`oklch(89% 0.01 233.65)`,
  borderControl: tone(color`oklch(89% 0.01 233.65)`, -0.03),
  primary: color`oklch(63% 0.1 230.71)`,
  success: color`oklch(61% 0.1 155.22)`,
  warning: color`oklch(62% 0.07 245.49)`,
  error: color`oklch(58% 0.08 245.16)`,
  purple: color`oklch(59% 0.1 303.62)`,
};

const uiColors = {
  base: {
    foreground: color(base.fg),
    foregroundMuted: color(base.fgMuted),
    foregroundSubtle: color(base.fgSubtle),
    foregroundSecondary: color(tone(base.fg, 0.09)),
    foregroundInverse: color`oklch(100% 0 0)`,
    disabled: color(tone(base.fgSubtle, 0.09)),
    transparent: alpha(color`oklch(0% 0 0)`, 0),
  },
  surface: {
    editor: color(base.bg),
    workbench: color(base.bgWorkbench),
    workbenchAlt: color(tone(base.bgWorkbench, -0.02)),
    control: color(base.bgControl),
    controlHover: color(tone(base.bgControl, 0.02)),
    hover: alpha(base.fgSubtle, 0.18),
    selection: alpha(base.primary, 0.1),
    selectionStrong: alpha(base.primary, 0.15),
    selectionActive: alpha(base.primary, 0.25),
    selectionMatch: alpha(base.primary, 0.2),
    request: color(base.bgWorkbench),
    requestHover: color(tone(base.bgWorkbench, -0.03)),
    indentGuide: color(tone(base.border, 0.04)),
  },
  border: {
    default: alpha(base.border, 1),
    muted: color(base.border),
    control: color(base.borderControl),
    controlSoft: alpha(base.borderControl, 0.4),
    elevated: alpha(tone(base.border, -0.01), 1),
    separator: color(tone(base.border, 0.04)),
    focus: alpha(base.primary, 0.7),
  },
  accent: {
    primary: color(base.primary),
    primaryHover: color(tone(base.primary, 0.02)),
    primaryText: color(tone(base.primary, -0.04)),
    blueSoft: alpha(base.primary, 0.14),
    selectedTop: color(tone(base.primary, 0.09)),
  },
  state: {
    success: color(base.success),
    modified: color(tone(base.primary, -0.03)),
    warning: color(base.warning),
    warningBadge: color(tone(base.warning, 0.09)),
    warningSoft: alpha(base.warning, 0.25),
    error: color(base.error),
    errorSoft: alpha(base.error, 0.25),
    infoSoft: alpha(base.primary, 0.1),
  },
  scrollbar: {
    background: alpha(base.fgSubtle, 0.15),
    hover: alpha(base.fgSubtle, 0.25),
    active: alpha(base.fgSubtle, 0.33),
  },
  charts: {
    foreground: color(base.fg),
    lines: alpha(base.fg, 0.4),
    blue: color`oklch(70% 0.15 252.85)`,
    red: color(base.error),
    yellow: color(tone(base.primary, -0.03)),
    orange: color(tone(base.primary, -0.03)),
    green: color(base.success),
    purple: color(base.purple),
  },
};

const groups = {
  workbench: {
    "activityBar.activeBorder": uiColors.base.foreground,
    "activityBar.background": uiColors.surface.workbench,
    "activityBar.border": uiColors.border.default,
    "activityBar.foreground": uiColors.base.foreground,
    "activityBar.inactiveForeground": uiColors.base.foregroundMuted,
    "activityBarBadge.background": uiColors.accent.primary,
    "activityBarBadge.foreground": uiColors.base.foregroundInverse,
    "badge.background": uiColors.accent.primary,
    "badge.foreground": uiColors.base.foregroundInverse,
    "button.background": uiColors.accent.primary,
    "button.border": uiColors.border.separator,
    "button.foreground": uiColors.base.foregroundInverse,
    "button.hoverBackground": uiColors.accent.primaryHover,
    "button.secondaryBackground": uiColors.surface.control,
    "button.secondaryForeground": uiColors.base.foreground,
    "button.secondaryHoverBackground": uiColors.surface.controlHover,
    "chat.slashCommandBackground": uiColors.accent.blueSoft,
    "chat.slashCommandForeground": uiColors.accent.primaryText,
    "chat.editedFileForeground": alpha(color`oklch(61% 0.06 243.03)`, 1),
    "checkbox.background": uiColors.surface.control,
    "checkbox.border": uiColors.border.control,
    descriptionForeground: uiColors.base.foregroundMuted,
    "dropdown.background": uiColors.surface.editor,
    "dropdown.border": uiColors.border.control,
    "dropdown.foreground": uiColors.base.foreground,
    "dropdown.listBackground": uiColors.surface.editor,
    "editor.background": uiColors.surface.editor,
    "editor.foreground": uiColors.base.foreground,
    "editor.inactiveSelectionBackground": uiColors.surface.selection,
    "editor.selectionHighlightBackground": alpha(base.primary, 0.08),
    "editorGroup.border": uiColors.border.muted,
    "editorGroupHeader.tabsBackground": uiColors.surface.workbench,
    "editorGroupHeader.tabsBorder": uiColors.border.default,
    "editorGutter.addedBackground": uiColors.state.success,
    "editorGutter.deletedBackground": uiColors.state.error,
    "editorGutter.modifiedBackground": uiColors.accent.primaryText,
    "editorLineNumber.activeForeground": uiColors.base.foreground,
    "editorLineNumber.foreground": uiColors.base.foregroundMuted,
    "editorOverviewRuler.border": uiColors.border.default,
    "editorSuggestWidget.background": uiColors.surface.workbench,
    "editorWidget.background": uiColors.surface.workbench,
    errorForeground: uiColors.state.error,
    focusBorder: uiColors.border.focus,
    foreground: uiColors.base.foreground,
    "icon.foreground": uiColors.base.foregroundMuted,
    "input.background": uiColors.surface.editor,
    "input.border": uiColors.border.controlSoft,
    "input.foreground": uiColors.base.foreground,
    "input.placeholderForeground": uiColors.base.foregroundSubtle,
    "inputOption.activeBackground": uiColors.surface.selectionStrong,
    "inputOption.activeBorder": uiColors.border.default,
    "inputOption.activeForeground": uiColors.base.foreground,
    "keybindingLabel.foreground": uiColors.base.foregroundSecondary,
    "list.activeSelectionBackground": uiColors.surface.selection,
    "list.activeSelectionForeground": uiColors.base.foreground,
    "list.activeSelectionIconForeground": uiColors.base.foreground,
    "list.hoverBackground": uiColors.surface.hover,
    "list.focusAndSelectionOutline": uiColors.accent.primaryText,
    "menu.border": uiColors.border.elevated,
    "menu.selectionBackground": uiColors.surface.selection,
    "menu.selectionForeground": uiColors.base.foreground,
  },
  notebooksAndNotifications: {
    "notebook.cellBorderColor": uiColors.border.default,
    "notebook.selectedCellBackground": color`oklch(89% 0.03 224.26 / 31%)`,
    "notificationCenterHeader.background": uiColors.surface.workbench,
    "notificationCenterHeader.foreground": uiColors.base.foreground,
    "notifications.background": uiColors.surface.workbench,
    "notifications.border": uiColors.border.default,
    "notifications.foreground": uiColors.base.foreground,
  },
  panelsAndSidebar: {
    "panel.background": uiColors.surface.workbench,
    "panel.border": uiColors.border.default,
    "panelInput.border": uiColors.border.default,
    "panelTitle.activeBorder": uiColors.base.foreground,
    "panelTitle.activeForeground": uiColors.base.foreground,
    "panelTitle.inactiveForeground": uiColors.base.foregroundMuted,
    "peekViewEditor.matchHighlightBackground": uiColors.surface.selectionMatch,
    "peekViewResult.background": uiColors.surface.workbench,
    "peekViewResult.matchHighlightBackground": uiColors.surface.selectionMatch,
    "pickerGroup.border": uiColors.border.separator,
    "pickerGroup.foreground": uiColors.base.foreground,
    "ports.iconRunningProcessForeground": uiColors.state.success,
    "progressBar.background": uiColors.accent.primary,
    "quickInput.background": uiColors.surface.workbench,
    "quickInput.foreground": uiColors.base.foreground,
    "searchEditor.textInputBorder": uiColors.border.control,
    "settings.dropdownBackground": uiColors.surface.editor,
    "settings.dropdownBorder": uiColors.border.control,
    "settings.headerForeground": uiColors.base.foreground,
    "settings.modifiedItemIndicator": color`oklch(65% 0.12 85.47 / 40%)`,
    "settings.numberInputBorder": uiColors.border.control,
    "settings.textInputBorder": uiColors.border.control,
    "sideBar.background": uiColors.surface.workbench,
    "sideBar.border": uiColors.border.default,
    "sideBar.foreground": uiColors.base.foreground,
    "sideBarSectionHeader.background": uiColors.surface.workbench,
    "sideBarSectionHeader.border": uiColors.border.default,
    "sideBarSectionHeader.foreground": uiColors.base.foreground,
    "sideBarTitle.foreground": uiColors.base.foreground,
  },
  chrome: {
    "statusBar.background": uiColors.surface.workbench,
    "statusBar.foreground": uiColors.base.foregroundMuted,
    "statusBar.border": uiColors.border.default,
    "statusBarItem.hoverBackground": uiColors.surface.hover,
    "statusBarItem.hoverForeground": uiColors.base.foreground,
    "statusBarItem.compactHoverBackground": color`oklch(88% 0.01 242.85)`,
    "statusBar.debuggingBackground": uiColors.accent.primary,
    "statusBar.debuggingForeground": uiColors.base.foregroundInverse,
    "statusBar.focusBorder": uiColors.border.focus,
    "statusBar.noFolderBackground": uiColors.surface.workbenchAlt,
    "statusBarItem.errorBackground": uiColors.state.error,
    "statusBarItem.focusBorder": uiColors.border.focus,
    "statusBarItem.prominentBackground": alpha(base.primary, 0.85),
    "statusBarItem.remoteBackground": uiColors.accent.primaryText,
    "statusBarItem.remoteForeground": uiColors.base.foregroundInverse,
    "tab.activeBackground": uiColors.surface.editor,
    "tab.activeBorder": uiColors.surface.editor,
    "tab.activeBorderTop": uiColors.base.foreground,
    "tab.activeForeground": uiColors.base.foreground,
    "tab.selectedBorderTop": uiColors.accent.selectedTop,
    "tab.border": uiColors.border.default,
    "tab.hoverBackground": uiColors.surface.editor,
    "tab.inactiveBackground": uiColors.surface.workbench,
    "tab.inactiveForeground": uiColors.base.foregroundMuted,
    "tab.lastPinnedBorder": uiColors.border.default,
    "tab.unfocusedActiveBorder": uiColors.surface.controlHover,
    "tab.unfocusedActiveBorderTop": uiColors.border.muted,
    "tab.unfocusedHoverBackground": uiColors.surface.controlHover,
  },
  terminal: {
    "terminalCursor.foreground": uiColors.base.foreground,
    "terminal.foreground": uiColors.base.foregroundSecondary,
    "terminal.inactiveSelectionBackground": color`oklch(93% 0.02 222.69)`,
    "terminal.tab.activeBorder": color`oklch(59% 0.1 231.68)`,
  },
  textContent: {
    "textBlockQuote.background": uiColors.surface.control,
    "textBlockQuote.border": uiColors.border.default,
    "textCodeBlock.background": uiColors.surface.control,
    "textLink.activeForeground": uiColors.accent.primary,
    "textLink.foreground": uiColors.accent.primary,
    "textPreformat.foreground": uiColors.base.foregroundMuted,
    "textPreformat.background": uiColors.surface.workbenchAlt,
    "textSeparator.foreground": uiColors.border.separator,
    "titleBar.activeBackground": uiColors.surface.workbench,
    "titleBar.activeForeground": uiColors.base.foregroundMuted,
    "titleBar.border": uiColors.border.default,
    "titleBar.inactiveBackground": uiColors.surface.workbench,
    "titleBar.inactiveForeground": uiColors.base.foregroundMuted,
    "welcomePage.tileBackground": uiColors.surface.workbenchAlt,
    "widget.border": uiColors.border.elevated,
    disabledForeground: uiColors.base.disabled,
    "checkbox.foreground": uiColors.base.foregroundMuted,
  },
  validation: {
    "inputValidation.infoBackground": uiColors.state.infoSoft,
    "inputValidation.infoBorder": uiColors.accent.primary,
    "inputValidation.infoForeground": uiColors.base.foreground,
    "inputValidation.warningBackground": color`oklch(95% 0.03 87.85)`,
    "inputValidation.warningBorder": uiColors.state.warning,
    "inputValidation.warningForeground": uiColors.base.foreground,
    "inputValidation.errorBackground": color`oklch(94% 0.02 34.3)`,
    "inputValidation.errorBorder": uiColors.state.error,
    "inputValidation.errorForeground": uiColors.base.foreground,
  },
  listsAndMenus: {
    "scrollbar.shadow": uiColors.base.transparent,
    "widget.shadow": uiColors.base.transparent,
    "editorStickyScroll.shadow": uiColors.base.transparent,
    "editorStickyScrollHover.background": uiColors.surface.workbenchAlt,
    "editorStickyScroll.border": uiColors.border.default,
    "sideBarStickyScroll.shadow": uiColors.base.transparent,
    "panelStickyScroll.shadow": uiColors.base.transparent,
    "listFilterWidget.shadow": uiColors.base.transparent,
    "scrollbarSlider.background": uiColors.scrollbar.background,
    "scrollbarSlider.hoverBackground": uiColors.scrollbar.hover,
    "scrollbarSlider.activeBackground": uiColors.scrollbar.active,
    "list.inactiveSelectionBackground": uiColors.surface.hover,
    "list.inactiveSelectionForeground": uiColors.base.foreground,
    "list.hoverForeground": uiColors.base.foreground,
    "list.dropBackground": alpha(base.primary, 0.08),
    "list.focusBackground": uiColors.surface.selection,
    "list.focusForeground": uiColors.base.foreground,
    "list.focusOutline": uiColors.border.focus,
    "list.highlightForeground": uiColors.accent.primary,
    "list.invalidItemForeground": uiColors.base.disabled,
    "list.errorForeground": uiColors.state.error,
    "list.warningForeground": uiColors.state.modified,
    "activityBar.activeFocusBorder": uiColors.border.focus,
    "activityBarTop.activeBorder": uiColors.base.foreground,
    "menubar.selectionBackground": uiColors.surface.control,
    "menubar.selectionForeground": uiColors.base.foreground,
    "menu.background": uiColors.surface.workbench,
    "menu.foreground": uiColors.base.foreground,
    "menu.separatorBackground": uiColors.border.separator,
    "commandCenter.foreground": uiColors.base.foreground,
    "commandCenter.activeForeground": uiColors.base.foreground,
    "commandCenter.background": uiColors.surface.workbench,
    "commandCenter.activeBackground": uiColors.surface.hover,
    "commandCenter.border": uiColors.border.control,
  },
  editor: {
    "editorCursor.foreground": uiColors.base.foreground,
    "editor.selectionBackground": uiColors.surface.selectionActive,
    "editor.wordHighlightBackground": uiColors.surface.selectionStrong,
    "editor.wordHighlightStrongBackground": uiColors.surface.selectionStrong,
    "editor.findMatchBackground": uiColors.surface.selectionActive,
    "editor.findMatchHighlightBackground": uiColors.surface.selection,
    "editor.findRangeHighlightBackground": uiColors.surface.control,
    "editor.hoverHighlightBackground": uiColors.surface.control,
    "editor.lineHighlightBackground": alpha(uiColors.surface.control, 0.4),
    "editor.rangeHighlightBackground": uiColors.surface.control,
    "editorLink.activeForeground": uiColors.accent.primary,
    "editorWhitespace.foreground": alpha(uiColors.base.foregroundMuted, 0.25),
    "editorIndentGuide.background1": alpha(uiColors.surface.indentGuide, 0.25),
    "editorIndentGuide.activeBackground1": uiColors.surface.indentGuide,
    "editorRuler.foreground": uiColors.surface.indentGuide,
    "editorCodeLens.foreground": uiColors.base.foregroundMuted,
    "editorBracketMatch.background": uiColors.surface.selectionActive,
    "editorBracketHighlight.foreground1": color`oklch(70% 0 0)`,
    "editorBracketHighlight.foreground2": color`oklch(72% 0 0)`,
    "editorBracketHighlight.foreground3": color`oklch(74% 0 0)`,
    "editorBracketHighlight.foreground4": color`oklch(76% 0 0)`,
    "editorBracketHighlight.foreground5": color`oklch(74% 0 0)`,
    "editorBracketHighlight.foreground6": color`oklch(72% 0 0)`,
    "editorWidget.border": uiColors.border.elevated,
    "editorWidget.foreground": uiColors.base.foreground,
    "editorSuggestWidget.border": uiColors.border.elevated,
    "editorSuggestWidget.foreground": uiColors.base.foreground,
    "editorSuggestWidget.highlightForeground": uiColors.accent.primary,
    "editorSuggestWidget.selectedBackground": uiColors.surface.selectionStrong,
    "editorHoverWidget.background": uiColors.surface.workbench,
    "editorHoverWidget.border": uiColors.border.elevated,
    "peekView.border": uiColors.accent.primary,
    "peekViewEditor.background": uiColors.surface.workbench,
    "peekViewResult.fileForeground": uiColors.base.foreground,
    "peekViewResult.lineForeground": uiColors.base.foregroundMuted,
    "peekViewResult.selectionBackground": uiColors.surface.selectionStrong,
    "peekViewResult.selectionForeground": uiColors.base.foreground,
    "peekViewTitle.background": uiColors.surface.workbench,
    "peekViewTitleDescription.foreground": uiColors.base.foregroundMuted,
    "peekViewTitleLabel.foreground": uiColors.base.foreground,
  },
  diffAndGit: {
    "diffEditor.insertedTextBackground": alpha(base.success, 0.15),
    "diffEditor.removedTextBackground": uiColors.state.errorSoft,
    "editorOverviewRuler.findMatchForeground": alpha(base.primary, 0.6),
    "editorOverviewRuler.modifiedForeground": uiColors.accent.primary,
    "editorOverviewRuler.addedForeground": uiColors.state.success,
    "editorOverviewRuler.deletedForeground": uiColors.state.error,
    "editorOverviewRuler.errorForeground": uiColors.state.error,
    "editorOverviewRuler.warningForeground": uiColors.state.modified,
    "editorGutter.background": uiColors.surface.editor,
    "statusBar.noFolderForeground": uiColors.base.foregroundMuted,
    "statusBarItem.activeBackground": uiColors.border.separator,
    "statusBarItem.prominentForeground": uiColors.base.foregroundInverse,
    "statusBarItem.prominentHoverBackground": uiColors.accent.primary,
    "toolbar.hoverBackground": alpha(base.fg, 0.06),
    "tab.hoverForeground": uiColors.base.foreground,
    "tab.unfocusedActiveBackground": uiColors.surface.workbench,
    "tab.unfocusedActiveForeground": uiColors.base.foregroundMuted,
    "tab.unfocusedInactiveBackground": uiColors.surface.workbench,
    "tab.unfocusedInactiveForeground": uiColors.base.disabled,
    "breadcrumb.foreground": uiColors.base.foregroundMuted,
    "breadcrumb.background": uiColors.surface.editor,
    "breadcrumb.focusForeground": uiColors.base.foreground,
    "breadcrumb.activeSelectionForeground": uiColors.base.foreground,
    "breadcrumbPicker.background": uiColors.surface.workbench,
    "notificationCenter.border": uiColors.border.default,
    "notificationToast.border": uiColors.border.default,
    "notificationLink.foreground": uiColors.accent.primary,
    "notificationsWarningIcon.foreground": uiColors.state.warning,
    "notificationsErrorIcon.foreground": uiColors.state.error,
    "notificationsInfoIcon.foreground": uiColors.accent.primary,
    "activityWarningBadge.foreground": uiColors.base.foreground,
    "activityWarningBadge.background": uiColors.state.warningBadge,
    "activityErrorBadge.foreground": uiColors.base.foregroundInverse,
    "activityErrorBadge.background": uiColors.state.error,
    "extensionButton.prominentBackground": uiColors.accent.primary,
    "extensionButton.prominentForeground": uiColors.base.foregroundInverse,
    "extensionButton.prominentHoverBackground": uiColors.accent.primaryHover,
    "quickInputList.focusBackground": uiColors.surface.selection,
    "quickInputList.focusForeground": uiColors.base.foreground,
    "quickInputList.focusIconForeground": uiColors.base.foreground,
    "terminal.selectionBackground": uiColors.surface.selectionStrong,
    "terminalCursor.background": uiColors.surface.editor,
    "gitDecoration.addedResourceForeground": uiColors.state.success,
    "gitDecoration.modifiedResourceForeground": uiColors.state.modified,
    "gitDecoration.deletedResourceForeground": uiColors.state.error,
    "gitDecoration.untrackedResourceForeground": uiColors.state.success,
    "gitDecoration.ignoredResourceForeground": uiColors.base.foregroundSubtle,
    "gitDecoration.conflictingResourceForeground": uiColors.state.error,
    "gitDecoration.stageModifiedResourceForeground": color`oklch(60% 0.07 245.42 / 0%)`,
    "gitDecoration.stageDeletedResourceForeground": color`oklch(58% 0.08 245.16 / 0%)`,
    "commandCenter.activeBorder": uiColors.border.control,
  },
  chat: {
    "statusBarItem.prominentHoverForeground": uiColors.base.foregroundInverse,
    "quickInputTitle.background": uiColors.surface.workbench,
    "chat.requestBubbleBackground": uiColors.surface.request,
    "chat.requestBubbleHoverBackground": uiColors.surface.requestHover,
    "chat.thinkingShimmer": uiColors.base.foregroundSubtle,
    "editorCommentsWidget.rangeBackground": uiColors.surface.request,
    "editorCommentsWidget.rangeActiveBackground": uiColors.surface.requestHover,
  },
  chartsAndInline: {
    "charts.foreground": uiColors.charts.foreground,
    "charts.lines": uiColors.charts.lines,
    "charts.blue": uiColors.charts.blue,
    "charts.red": uiColors.charts.red,
    "charts.yellow": uiColors.charts.yellow,
    "charts.orange": uiColors.charts.orange,
    "charts.green": uiColors.charts.green,
    "charts.purple": uiColors.charts.purple,
    "agentStatusIndicator.background": uiColors.surface.editor,
    "inlineChat.border": uiColors.base.transparent,
    "minimapSlider.background": uiColors.scrollbar.background,
    "minimapSlider.hoverBackground": uiColors.scrollbar.hover,
    "minimapSlider.activeBackground": uiColors.scrollbar.active,
  },
};

export const LightUiTheme = flattenColorGroups(groups);
