import { alpha, color, flattenColorGroups, oklch, tone } from "./colors";

const base = {
  bg: oklch(1, 0),
  bgWorkbench: oklch(0.97, 0, 228.78),
  bgControl: oklch(0.94, 0.01, 228.82),
  fg: oklch(0.31, 0.01, 242),
  fgMuted: oklch(0.58, 0.02, 250.38),
  fgSubtle: oklch(0.67, 0.02, 245.2),
  border: oklch(0.89, 0.01, 233.65),
  borderControl: oklch(0.86, 0.01, 238.53),
  primary: oklch(0.63, 0.1, 230.71),
  success: oklch(0.61, 0.1, 155.22),
  warning: oklch(0.62, 0.07, 245.49),
  error: oklch(0.58, 0.08, 245.16),
  purple: oklch(0.59, 0.1, 303.62),
};

const uiColors = {
  base: {
    foreground: color(base.fg),
    foregroundMuted: color(base.fgMuted),
    foregroundSubtle: color(base.fgSubtle),
    foregroundSecondary: color(tone(base.fg, 0.09)),
    foregroundInverse: color(oklch(1, 0)),
    disabled: color(oklch(0.76, 0.01, 248.02)),
    transparent: alpha(oklch(0, 0), 0),
  },
  surface: {
    editor: color(base.bg),
    workbench: color(base.bgWorkbench),
    workbenchAlt: color(tone(base.bgWorkbench, -0.02)),
    control: color(base.bgControl),
    controlHover: color(tone(base.bgControl, 0.02)),
    hover: alpha(base.fgSubtle, 0.18),
    selection: alpha(base.primary, 0.1),
    selectionStrong: alpha(base.primary, 0.15),
    selectionActive: alpha(base.primary, 0.25),
    selectionMatch: alpha(base.primary, 0.2),
    request: color(tone(base.bg, -0.03)),
    requestHover: color(tone(base.bgControl, -0.01)),
    indentGuide: color(oklch(0.93, 0.01, 233.65)),
  },
  border: {
    default: alpha(base.border, 1),
    muted: color(base.border),
    control: color(base.borderControl),
    controlSoft: alpha(base.borderControl, 0.4),
    elevated: alpha(oklch(0.89, 0.01, 236.57), 1),
    separator: color(oklch(0.93, 0.01, 233.65)),
    focus: alpha(base.primary, 0.7),
  },
  accent: {
    primary: color(base.primary),
    primaryHover: color(oklch(0.65, 0.11, 230.6)),
    primaryText: color(oklch(0.59, 0.1, 231.68)),
    blueSoft: alpha(base.primary, 0.14),
    selectedTop: color(oklch(0.72, 0.08, 232.61)),
  },
  state: {
    success: color(base.success),
    modified: color(oklch(0.6, 0.07, 245.42)),
    warning: color(base.warning),
    warningBadge: color(oklch(0.71, 0.06, 243.57)),
    warningSoft: alpha(base.warning, 0.25),
    error: color(base.error),
    errorSoft: alpha(base.error, 0.25),
    infoSoft: color(oklch(0.95, 0.01, 219.62)),
  },
  scrollbar: {
    background: alpha(base.fgSubtle, 0.15),
    hover: alpha(base.fgSubtle, 0.25),
    active: alpha(base.fgSubtle, 0.33),
  },
  charts: {
    foreground: color(base.fg),
    lines: alpha(base.fg, 0.4),
    blue: color(oklch(0.7, 0.15, 252.85)),
    red: color(base.error),
    yellow: color(oklch(0.6, 0.07, 245.42)),
    orange: color(oklch(0.6, 0.07, 244.12)),
    green: color(base.success),
    purple: color(base.purple),
  },
};

const groups = {
  workbench: {
    "activityBar.activeBorder": uiColors.base.foreground,
    "activityBar.background": uiColors.surface.workbench,
    "activityBar.border": uiColors.border.default,
    "activityBar.foreground": uiColors.base.foreground,
    "activityBar.inactiveForeground": uiColors.base.foregroundMuted,
    "activityBarBadge.background": uiColors.accent.primary,
    "activityBarBadge.foreground": uiColors.base.foregroundInverse,
    "badge.background": uiColors.accent.primary,
    "badge.foreground": uiColors.base.foregroundInverse,
    "button.background": uiColors.accent.primary,
    "button.border": uiColors.border.separator,
    "button.foreground": uiColors.base.foregroundInverse,
    "button.hoverBackground": uiColors.accent.primaryHover,
    "button.secondaryBackground": uiColors.surface.control,
    "button.secondaryForeground": uiColors.base.foreground,
    "button.secondaryHoverBackground": uiColors.surface.controlHover,
    "chat.slashCommandBackground": uiColors.accent.blueSoft,
    "chat.slashCommandForeground": uiColors.accent.primaryText,
    "chat.editedFileForeground": alpha(oklch(0.61, 0.06, 243.03), 1),
    "checkbox.background": uiColors.surface.control,
    "checkbox.border": uiColors.border.control,
    descriptionForeground: uiColors.base.foregroundMuted,
    "dropdown.background": uiColors.surface.editor,
    "dropdown.border": uiColors.border.control,
    "dropdown.foreground": uiColors.base.foreground,
    "dropdown.listBackground": uiColors.surface.editor,
    "editor.background": uiColors.surface.editor,
    "editor.foreground": uiColors.base.foreground,
    "editor.inactiveSelectionBackground": uiColors.surface.selection,
    "editor.selectionHighlightBackground": alpha(base.primary, 0.08),
    "editorGroup.border": uiColors.border.muted,
    "editorGroupHeader.tabsBackground": uiColors.surface.workbench,
    "editorGroupHeader.tabsBorder": uiColors.border.default,
    "editorGutter.addedBackground": uiColors.state.success,
    "editorGutter.deletedBackground": uiColors.state.error,
    "editorGutter.modifiedBackground": uiColors.accent.primaryText,
    "editorIndentGuide.background1": uiColors.border.control,
    "editorLineNumber.activeForeground": uiColors.base.foreground,
    "editorLineNumber.foreground": uiColors.base.foregroundMuted,
    "editorOverviewRuler.border": uiColors.border.default,
    "editorSuggestWidget.background": uiColors.surface.workbench,
    "editorWidget.background": uiColors.surface.workbench,
    errorForeground: uiColors.state.error,
    focusBorder: uiColors.border.focus,
    foreground: uiColors.base.foreground,
    "icon.foreground": uiColors.base.foregroundMuted,
    "input.background": uiColors.surface.editor,
    "input.border": uiColors.border.controlSoft,
    "input.foreground": uiColors.base.foreground,
    "input.placeholderForeground": uiColors.base.foregroundSubtle,
    "inputOption.activeBackground": uiColors.surface.selectionStrong,
    "inputOption.activeBorder": uiColors.border.default,
    "inputOption.activeForeground": uiColors.base.foreground,
    "keybindingLabel.foreground": uiColors.base.foregroundSecondary,
    "list.activeSelectionBackground": uiColors.surface.selection,
    "list.activeSelectionForeground": uiColors.base.foreground,
    "list.activeSelectionIconForeground": uiColors.base.foreground,
    "list.hoverBackground": uiColors.surface.hover,
    "list.focusAndSelectionOutline": uiColors.accent.primaryText,
    "menu.border": uiColors.border.elevated,
    "menu.selectionBackground": uiColors.surface.selection,
    "menu.selectionForeground": uiColors.base.foreground,
  },
  notebooksAndNotifications: {
    "notebook.cellBorderColor": uiColors.border.default,
    "notebook.selectedCellBackground": oklch(0.89, 0.03, 224.26, 0.31),
    "notificationCenterHeader.background": uiColors.surface.workbench,
    "notificationCenterHeader.foreground": uiColors.base.foreground,
    "notifications.background": uiColors.surface.workbench,
    "notifications.border": uiColors.border.default,
    "notifications.foreground": uiColors.base.foreground,
  },
  panelsAndSidebar: {
    "panel.background": uiColors.surface.workbench,
    "panel.border": uiColors.border.default,
    "panelInput.border": uiColors.border.default,
    "panelTitle.activeBorder": uiColors.base.foreground,
    "panelTitle.activeForeground": uiColors.base.foreground,
    "panelTitle.inactiveForeground": uiColors.base.foregroundMuted,
    "peekViewEditor.matchHighlightBackground": uiColors.surface.selectionMatch,
    "peekViewResult.background": uiColors.surface.workbench,
    "peekViewResult.matchHighlightBackground": uiColors.surface.selectionMatch,
    "pickerGroup.border": uiColors.border.separator,
    "pickerGroup.foreground": uiColors.base.foreground,
    "ports.iconRunningProcessForeground": uiColors.state.success,
    "progressBar.background": uiColors.accent.primary,
    "quickInput.background": uiColors.surface.workbench,
    "quickInput.foreground": uiColors.base.foreground,
    "searchEditor.textInputBorder": uiColors.border.control,
    "settings.dropdownBackground": uiColors.surface.editor,
    "settings.dropdownBorder": uiColors.border.control,
    "settings.headerForeground": uiColors.base.foreground,
    "settings.modifiedItemIndicator": oklch(0.65, 0.12, 85.47, 0.4),
    "settings.numberInputBorder": uiColors.border.control,
    "settings.textInputBorder": uiColors.border.control,
    "sideBar.background": uiColors.surface.workbench,
    "sideBar.border": uiColors.border.default,
    "sideBar.foreground": uiColors.base.foreground,
    "sideBarSectionHeader.background": uiColors.surface.workbench,
    "sideBarSectionHeader.border": uiColors.border.default,
    "sideBarSectionHeader.foreground": uiColors.base.foreground,
    "sideBarTitle.foreground": uiColors.base.foreground,
  },
  chrome: {
    "statusBar.background": uiColors.surface.workbench,
    "statusBar.foreground": uiColors.base.foregroundMuted,
    "statusBar.border": uiColors.border.default,
    "statusBarItem.hoverBackground": uiColors.surface.hover,
    "statusBarItem.hoverForeground": uiColors.base.foreground,
    "statusBarItem.compactHoverBackground": oklch(0.88, 0.01, 242.85),
    "statusBar.debuggingBackground": uiColors.accent.primary,
    "statusBar.debuggingForeground": uiColors.base.foregroundInverse,
    "statusBar.focusBorder": uiColors.border.focus,
    "statusBar.noFolderBackground": uiColors.surface.workbenchAlt,
    "statusBarItem.errorBackground": uiColors.state.error,
    "statusBarItem.focusBorder": uiColors.border.focus,
    "statusBarItem.prominentBackground": alpha(base.primary, 0.85),
    "statusBarItem.remoteBackground": uiColors.accent.primaryText,
    "statusBarItem.remoteForeground": uiColors.base.foregroundInverse,
    "tab.activeBackground": uiColors.surface.editor,
    "tab.activeBorder": uiColors.surface.editor,
    "tab.activeBorderTop": uiColors.base.foreground,
    "tab.activeForeground": uiColors.base.foreground,
    "tab.selectedBorderTop": uiColors.accent.selectedTop,
    "tab.border": uiColors.border.default,
    "tab.hoverBackground": uiColors.surface.editor,
    "tab.inactiveBackground": uiColors.surface.workbench,
    "tab.inactiveForeground": uiColors.base.foregroundMuted,
    "tab.lastPinnedBorder": uiColors.border.default,
    "tab.unfocusedActiveBorder": uiColors.surface.controlHover,
    "tab.unfocusedActiveBorderTop": uiColors.border.muted,
    "tab.unfocusedHoverBackground": uiColors.surface.controlHover,
  },
  terminal: {
    "terminalCursor.foreground": uiColors.base.foreground,
    "terminal.foreground": uiColors.base.foregroundSecondary,
    "terminal.inactiveSelectionBackground": oklch(0.93, 0.02, 222.69),
    "terminal.tab.activeBorder": oklch(0.59, 0.1, 231.68),
  },
  textContent: {
    "textBlockQuote.background": uiColors.surface.control,
    "textBlockQuote.border": uiColors.border.default,
    "textCodeBlock.background": uiColors.surface.control,
    "textLink.activeForeground": uiColors.accent.primary,
    "textLink.foreground": uiColors.accent.primary,
    "textPreformat.foreground": uiColors.base.foregroundMuted,
    "textPreformat.background": uiColors.surface.workbenchAlt,
    "textSeparator.foreground": uiColors.border.separator,
    "titleBar.activeBackground": uiColors.surface.workbench,
    "titleBar.activeForeground": uiColors.base.foregroundMuted,
    "titleBar.border": uiColors.border.default,
    "titleBar.inactiveBackground": uiColors.surface.workbench,
    "titleBar.inactiveForeground": uiColors.base.foregroundMuted,
    "welcomePage.tileBackground": uiColors.surface.workbenchAlt,
    "widget.border": uiColors.border.elevated,
    disabledForeground: uiColors.base.disabled,
    "checkbox.foreground": uiColors.base.foregroundMuted,
  },
  validation: {
    "inputValidation.infoBackground": uiColors.state.infoSoft,
    "inputValidation.infoBorder": uiColors.accent.primary,
    "inputValidation.infoForeground": uiColors.base.foreground,
    "inputValidation.warningBackground": oklch(0.95, 0.03, 87.85),
    "inputValidation.warningBorder": uiColors.state.warning,
    "inputValidation.warningForeground": uiColors.base.foreground,
    "inputValidation.errorBackground": oklch(0.94, 0.02, 34.3),
    "inputValidation.errorBorder": uiColors.state.error,
    "inputValidation.errorForeground": uiColors.base.foreground,
  },
  listsAndMenus: {
    "scrollbar.shadow": oklch(0, 0, 0, 0),
    "widget.shadow": oklch(0, 0, 0, 0),
    "editorStickyScroll.shadow": oklch(0, 0, 0, 0),
    "editorStickyScrollHover.background": uiColors.surface.workbenchAlt,
    "editorStickyScroll.border": uiColors.border.default,
    "sideBarStickyScroll.shadow": oklch(0, 0, 0, 0),
    "panelStickyScroll.shadow": oklch(0, 0, 0, 0),
    "listFilterWidget.shadow": oklch(0, 0, 0, 0),
    "scrollbarSlider.background": oklch(0.67, 0.02, 245.2, 0.15),
    "scrollbarSlider.hoverBackground": oklch(0.67, 0.02, 245.2, 0.25),
    "scrollbarSlider.activeBackground": oklch(0.67, 0.02, 245.2, 0.33),
    "list.inactiveSelectionBackground": oklch(0.89, 0.01, 243.67, 0.6),
    "list.inactiveSelectionForeground": uiColors.base.foreground,
    "list.hoverForeground": uiColors.base.foreground,
    "list.dropBackground": oklch(0.63, 0.1, 230.71, 0.08),
    "list.focusBackground": oklch(0.63, 0.1, 230.71, 0.1),
    "list.focusForeground": uiColors.base.foreground,
    "list.focusOutline": uiColors.border.focus,
    "list.highlightForeground": uiColors.accent.primary,
    "list.invalidItemForeground": uiColors.base.disabled,
    "list.errorForeground": uiColors.state.error,
    "list.warningForeground": uiColors.state.modified,
    "activityBar.activeFocusBorder": uiColors.border.focus,
    "activityBarTop.activeBorder": uiColors.base.foreground,
    "menubar.selectionBackground": uiColors.surface.control,
    "menubar.selectionForeground": uiColors.base.foreground,
    "menu.background": uiColors.surface.workbench,
    "menu.foreground": uiColors.base.foreground,
    "menu.separatorBackground": uiColors.border.separator,
    "commandCenter.foreground": uiColors.base.foreground,
    "commandCenter.activeForeground": uiColors.base.foreground,
    "commandCenter.background": uiColors.surface.workbench,
    "commandCenter.activeBackground": uiColors.surface.hover,
    "commandCenter.border": uiColors.border.control,
  },
  editor: {
    "editorCursor.foreground": uiColors.base.foreground,
    "editor.selectionBackground": uiColors.surface.selectionActive,
    "editor.wordHighlightBackground": uiColors.surface.selectionStrong,
    "editor.wordHighlightStrongBackground": uiColors.surface.selectionStrong,
    "editor.findMatchBackground": uiColors.surface.selectionActive,
    "editor.findMatchHighlightBackground": uiColors.surface.selection,
    "editor.findRangeHighlightBackground": uiColors.surface.control,
    "editor.hoverHighlightBackground": uiColors.surface.control,
    "editor.lineHighlightBackground": alpha(uiColors.surface.control, 0.4),
    "editor.rangeHighlightBackground": uiColors.surface.control,
    "editorLink.activeForeground": uiColors.accent.primary,
    "editorWhitespace.foreground": alpha(uiColors.base.foregroundMuted, 0.25),
    "editorIndentGuide.background": alpha(uiColors.surface.indentGuide, 0.25),
    "editorIndentGuide.activeBackground": uiColors.surface.indentGuide,
    "editorRuler.foreground": uiColors.surface.indentGuide,
    "editorCodeLens.foreground": uiColors.base.foregroundMuted,
    "editorBracketMatch.background": uiColors.surface.selectionActive,
    "editorBracketMatch.border": uiColors.border.default,
    "editorWidget.border": uiColors.border.elevated,
    "editorWidget.foreground": uiColors.base.foreground,
    "editorSuggestWidget.border": uiColors.border.elevated,
    "editorSuggestWidget.foreground": uiColors.base.foreground,
    "editorSuggestWidget.highlightForeground": uiColors.accent.primary,
    "editorSuggestWidget.selectedBackground": uiColors.surface.selectionStrong,
    "editorHoverWidget.background": uiColors.surface.workbench,
    "editorHoverWidget.border": uiColors.border.elevated,
    "peekView.border": uiColors.accent.primary,
    "peekViewEditor.background": uiColors.surface.workbench,
    "peekViewResult.fileForeground": uiColors.base.foreground,
    "peekViewResult.lineForeground": uiColors.base.foregroundMuted,
    "peekViewResult.selectionBackground": uiColors.surface.selectionStrong,
    "peekViewResult.selectionForeground": uiColors.base.foreground,
    "peekViewTitle.background": uiColors.surface.workbench,
    "peekViewTitleDescription.foreground": uiColors.base.foregroundMuted,
    "peekViewTitleLabel.foreground": uiColors.base.foreground,
  },
  diffAndGit: {
    "diffEditor.insertedTextBackground": oklch(0.61, 0.1, 155.22, 0.15),
    "diffEditor.removedTextBackground": oklch(0.58, 0.08, 245.16, 0.15),
    "editorOverviewRuler.findMatchForeground": oklch(0.63, 0.1, 230.71, 0.6),
    "editorOverviewRuler.modifiedForeground": oklch(0.63, 0.1, 230.71),
    "editorOverviewRuler.addedForeground": oklch(0.61, 0.1, 155.22),
    "editorOverviewRuler.deletedForeground": oklch(0.58, 0.08, 245.16),
    "editorOverviewRuler.errorForeground": oklch(0.58, 0.08, 245.16),
    "editorOverviewRuler.warningForeground": oklch(0.6, 0.07, 245.42),
    "editorGutter.background": uiColors.surface.editor,
    "statusBar.noFolderForeground": uiColors.base.foregroundMuted,
    "statusBarItem.activeBackground": uiColors.border.separator,
    "statusBarItem.prominentForeground": uiColors.base.foregroundInverse,
    "statusBarItem.prominentHoverBackground": uiColors.accent.primary,
    "toolbar.hoverBackground": oklch(0.31, 0.01, 242, 0.06),
    "tab.hoverForeground": uiColors.base.foreground,
    "tab.unfocusedActiveBackground": uiColors.surface.workbench,
    "tab.unfocusedActiveForeground": uiColors.base.foregroundMuted,
    "tab.unfocusedInactiveBackground": uiColors.surface.workbench,
    "tab.unfocusedInactiveForeground": uiColors.base.disabled,
    "breadcrumb.foreground": uiColors.base.foregroundMuted,
    "breadcrumb.background": uiColors.surface.editor,
    "breadcrumb.focusForeground": uiColors.base.foreground,
    "breadcrumb.activeSelectionForeground": uiColors.base.foreground,
    "breadcrumbPicker.background": uiColors.surface.workbench,
    "notificationCenter.border": uiColors.border.default,
    "notificationToast.border": uiColors.border.default,
    "notificationLink.foreground": uiColors.accent.primary,
    "notificationsWarningIcon.foreground": uiColors.state.warning,
    "notificationsErrorIcon.foreground": uiColors.state.error,
    "notificationsInfoIcon.foreground": uiColors.accent.primary,
    "activityWarningBadge.foreground": uiColors.base.foreground,
    "activityWarningBadge.background": uiColors.state.warningBadge,
    "activityErrorBadge.foreground": uiColors.base.foregroundInverse,
    "activityErrorBadge.background": uiColors.state.error,
    "extensionButton.prominentBackground": uiColors.accent.primary,
    "extensionButton.prominentForeground": uiColors.base.foregroundInverse,
    "extensionButton.prominentHoverBackground": oklch(0.65, 0.11, 230.6),
    "quickInputList.focusBackground": uiColors.surface.selection,
    "quickInputList.focusForeground": uiColors.base.foreground,
    "quickInputList.focusIconForeground": uiColors.base.foreground,
    "quickInputList.hoverBackground": oklch(0.95, 0.01, 236.56),
    "terminal.selectionBackground": oklch(0.63, 0.1, 230.71, 0.15),
    "terminalCursor.background": oklch(1, 0),
    "gitDecoration.addedResourceForeground": oklch(0.61, 0.1, 155.22),
    "gitDecoration.modifiedResourceForeground": oklch(0.6, 0.07, 245.42),
    "gitDecoration.deletedResourceForeground": oklch(0.58, 0.08, 245.16),
    "gitDecoration.untrackedResourceForeground": oklch(0.61, 0.1, 155.22),
    "gitDecoration.ignoredResourceForeground": oklch(0.67, 0.02, 245.2),
    "gitDecoration.conflictingResourceForeground": oklch(0.58, 0.08, 245.16),
    "gitDecoration.stageModifiedResourceForeground": oklch(
      0.6,
      0.07,
      245.42,
      0,
    ),
    "gitDecoration.stageDeletedResourceForeground": oklch(
      0.58,
      0.08,
      245.16,
      0,
    ),
    "commandCenter.activeBorder": uiColors.border.control,
    "quickInput.border": uiColors.border.control,
  },
  gaugesAndChat: {
    "gauge.foreground": oklch(0.63, 0.1, 230.71),
    "gauge.background": oklch(0.63, 0.1, 230.71, 0.25),
    "gauge.border": oklch(0.89, 0.01, 233.65, 1),
    "gauge.warningForeground": oklch(0.62, 0.07, 245.49),
    "gauge.warningBackground": oklch(0.62, 0.07, 245.49, 0.25),
    "gauge.errorForeground": oklch(0.58, 0.08, 245.16),
    "gauge.errorBackground": oklch(0.58, 0.08, 245.16, 0.25),
    "statusBarItem.prominentHoverForeground": uiColors.base.foregroundInverse,
    "quickInputTitle.background": uiColors.surface.workbench,
    "chat.requestBubbleBackground": oklch(0.97, 0.01, 214.34),
    "chat.requestBubbleHoverBackground": oklch(0.94, 0.02, 226.97),
    "chat.thinkingShimmer": oklch(0.67, 0.02, 245.2),
    "editorCommentsWidget.rangeBackground": oklch(0.97, 0.01, 214.34),
    "editorCommentsWidget.rangeActiveBackground": oklch(0.94, 0.02, 226.97),
  },
  chartsAndInline: {
    "charts.foreground": oklch(0.31, 0.01, 242),
    "charts.lines": oklch(0.31, 0.01, 242, 0.4),
    "charts.blue": oklch(0.7, 0.15, 252.85),
    "charts.red": oklch(0.58, 0.08, 245.16),
    "charts.yellow": oklch(0.6, 0.07, 245.42),
    "charts.orange": oklch(0.6, 0.07, 244.12),
    "charts.green": oklch(0.61, 0.1, 155.22),
    "charts.purple": oklch(0.59, 0.1, 303.62),
    "agentStatusIndicator.background": oklch(1, 0),
    "inlineChat.border": oklch(0, 0, 0, 0),
    "minimapSlider.background": oklch(0.67, 0.02, 245.2, 0.15),
    "minimapSlider.hoverBackground": oklch(0.67, 0.02, 245.2, 0.25),
    "minimapSlider.activeBackground": oklch(0.67, 0.02, 245.2, 0.33),
  },
};

export const LightUiTheme = flattenColorGroups(groups);
